/**
 * Public kernel facade for plugins.
 * Values live here; kernel types import from `@on-codemerge/kernel`.
 */
import {
  applyOp,
  applyOps,
  applyTransaction,
  clampSelection,
  cloneNode,
  collapsedAt,
  createDoc,
  createParagraph,
  createState,
  createText,
  deleteBackward,
  docFromJSON,
  docToJSON,
  getNodeAt,
  insertText,
  normalize,
  orderedRange,
  runCommand,
  selectionTextRange,
  splitBlock,
  textLength,
  toggleMark,
  selectionHasMark,
  rangeHasMark,
  offsetHasMark,
} from '@on-codemerge/kernel';

export const core = {
  applyOp,
  applyOps,
  applyTransaction,
  clampSelection,
  cloneNode,
  collapsedAt,
  createDoc,
  createParagraph,
  createState,
  createText,
  deleteBackward,
  docFromJSON,
  docToJSON,
  getNodeAt,
  insertText,
  normalize,
  orderedRange,
  offsetHasMark,
  rangeHasMark,
  runCommand,
  selectionHasMark,
  selectionTextRange,
  splitBlock,
  textLength,
  toggleMark,
} as const;
