/** Command → Unicode glyph (or keep as text for operators). */
export const GREEK: Record<string, string> = {
  alpha: 'α',
  beta: 'β',
  gamma: 'γ',
  delta: 'δ',
  epsilon: 'ε',
  zeta: 'ζ',
  eta: 'η',
  theta: 'θ',
  iota: 'ι',
  kappa: 'κ',
  lambda: 'λ',
  mu: 'μ',
  nu: 'ν',
  xi: 'ξ',
  pi: 'π',
  rho: 'ρ',
  sigma: 'σ',
  tau: 'τ',
  upsilon: 'υ',
  phi: 'φ',
  chi: 'χ',
  psi: 'ψ',
  omega: 'ω',
  Alpha: 'Α',
  Beta: 'Β',
  Gamma: 'Γ',
  Delta: 'Δ',
  Theta: 'Θ',
  Lambda: 'Λ',
  Pi: 'Π',
  Sigma: 'Σ',
  Phi: 'Φ',
  Psi: 'Ψ',
  Omega: 'Ω',
};

export const SYMBOLS: Record<string, string> = {
  pm: '±',
  mp: '∓',
  times: '×',
  div: '÷',
  cdot: '⋅',
  cdots: '⋯',
  ldots: '…',
  infty: '∞',
  leq: '≤',
  geq: '≥',
  neq: '≠',
  approx: '≈',
  equiv: '≡',
  sim: '∼',
  propto: '∝',
  partial: '∂',
  nabla: '∇',
  forall: '∀',
  exists: '∃',
  in: '∈',
  notin: '∉',
  subset: '⊂',
  supset: '⊃',
  cup: '∪',
  cap: '∩',
  emptyset: '∅',
  rightarrow: '→',
  leftarrow: '←',
  Rightarrow: '⇒',
  Leftarrow: '⇐',
  to: '→',
};

export const LARGE_OPS = new Set(['sum', 'int', 'prod', 'lim']);

export const FUNCS = new Set(['sin', 'cos', 'tan', 'log', 'ln', 'exp', 'max', 'min', 'det']);

export const SPACES: Record<string, 'thin' | 'med' | 'thick' | 'quad'> = {
  ',': 'thin',
  ';': 'med',
  quad: 'quad',
  qquad: 'quad',
};

export type BuildSymbol = { label: string; insert: string };

export const BUILD_GROUPS: { title: string; items: BuildSymbol[] }[] = [
  {
    title: 'structures',
    items: [
      { label: 'a/b', insert: '\\frac{#}{#}' },
      { label: '√', insert: '\\sqrt{#}' },
      { label: 'ⁿ√', insert: '\\sqrt[#]{#}' },
      { label: 'xⁿ', insert: '^{#}' },
      { label: 'xₙ', insert: '_{#}' },
      { label: '( )', insert: '\\left(#\\right)' },
    ],
  },
  {
    title: 'calculus',
    items: [
      { label: '∑', insert: '\\sum_{#}^{#}' },
      { label: '∫', insert: '\\int_{#}^{#}' },
      { label: '∏', insert: '\\prod_{#}^{#}' },
      { label: 'lim', insert: '\\lim_{#}' },
    ],
  },
  {
    title: 'ops',
    items: [
      { label: '+', insert: '+' },
      { label: '−', insert: '-' },
      { label: '×', insert: '\\times' },
      { label: '÷', insert: '\\div' },
      { label: '·', insert: '\\cdot' },
      { label: '=', insert: '=' },
      { label: '≠', insert: '\\neq' },
      { label: '≤', insert: '\\leq' },
      { label: '≥', insert: '\\geq' },
      { label: '±', insert: '\\pm' },
    ],
  },
  {
    title: 'funcs',
    items: [
      { label: 'sin', insert: '\\sin' },
      { label: 'cos', insert: '\\cos' },
      { label: 'tan', insert: '\\tan' },
      { label: 'log', insert: '\\log' },
      { label: 'ln', insert: '\\ln' },
    ],
  },
  {
    title: 'greek',
    items: [
      { label: 'α', insert: '\\alpha' },
      { label: 'β', insert: '\\beta' },
      { label: 'γ', insert: '\\gamma' },
      { label: 'δ', insert: '\\delta' },
      { label: 'θ', insert: '\\theta' },
      { label: 'λ', insert: '\\lambda' },
      { label: 'μ', insert: '\\mu' },
      { label: 'π', insert: '\\pi' },
      { label: 'σ', insert: '\\sigma' },
      { label: 'φ', insert: '\\phi' },
      { label: 'ω', insert: '\\omega' },
      { label: 'Σ', insert: '\\Sigma' },
      { label: 'Δ', insert: '\\Delta' },
      { label: '∞', insert: '\\infty' },
    ],
  },
];
