// constants.ts
export const AVAILABLE_STYLES: Record<string, string[]> = {
  color: [
    'red',
    'blue',
    'green',
    'yellow',
    'black',
    'white',
    'orange',
    'purple',
    'pink',
    'brown',
    'gray',
    'lightblue',
    'lightgreen',
    'lightyellow',
    'lightgray',
    'darkblue',
    'darkgreen',
    'darkred',
    'darkgray',
    'cyan',
    'magenta',
    'lime',
    'maroon',
    'navy',
    'olive',
    'teal',
    'silver',
    'gold',
    'indigo',
    'violet',
  ],
  'font-size': [
    '8px',
    '9px',
    '10px',
    '11px',
    '12px',
    '13px',
    '14px',
    '15px',
    '16px',
    '17px',
    '18px',
    '19px',
    '20px',
    '22px',
    '24px',
    '26px',
    '28px',
    '30px',
    '32px',
    '36px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'font-weight': [
    'normal',
    'bold',
    'bolder',
    'lighter',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
  ],
  'text-align': [
    'left',
    'center',
    'right',
    'justify',
    'start',
    'end',
    'inherit',
    'initial',
    'unset',
  ],
  'background-color': [
    'transparent',
    'red',
    'blue',
    'green',
    'yellow',
    'black',
    'white',
    'orange',
    'purple',
    'pink',
    'brown',
    'gray',
    'lightblue',
    'lightgreen',
    'lightyellow',
    'lightgray',
    'darkblue',
    'darkgreen',
    'darkred',
    'darkgray',
    'cyan',
    'magenta',
    'lime',
    'maroon',
    'navy',
    'olive',
    'teal',
    'silver',
    'gold',
    'indigo',
    'violet',
  ],
  'border-style': [
    'none',
    'solid',
    'dashed',
    'dotted',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
    'hidden',
  ],
  'border-width': [
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    'thin',
    'medium',
    'thick',
  ],
  'border-color': [
    'red',
    'blue',
    'green',
    'yellow',
    'black',
    'white',
    'orange',
    'purple',
    'pink',
    'brown',
    'gray',
    'lightblue',
    'lightgreen',
    'lightyellow',
    'lightgray',
    'darkblue',
    'darkgreen',
    'darkred',
    'darkgray',
    'cyan',
    'magenta',
    'lime',
    'maroon',
    'navy',
    'olive',
    'teal',
    'silver',
    'gold',
    'indigo',
    'violet',
  ],
  'margin-top': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'margin-bottom': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'margin-left': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'margin-right': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'padding-top': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'padding-bottom': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'padding-left': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'padding-right': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'line-height': [
    'normal',
    '1',
    '1.2',
    '1.4',
    '1.5',
    '1.6',
    '1.8',
    '2',
    '2.2',
    '2.4',
    '2.6',
    '2.8',
    '3',
  ],
  'font-family': [
    'Arial',
    'Arial Black',
    'Verdana',
    'Tahoma',
    'Trebuchet MS',
    'Times New Roman',
    'Georgia',
    'Garamond',
    'Courier New',
    'Brush Script MT',
    'Comic Sans MS',
    'Impact',
    'Lucida Console',
    'Palatino',
    'Bookman',
    'Avant Garde',
    'Courier',
    'Helvetica',
    'Geneva',
    'Optima',
    'Futura',
    'Baskerville',
    'Didot',
    'American Typewriter',
    'Andale Mono',
    'Monaco',
    'Bradley Hand',
    'Chalkduster',
    'Copperplate',
    'Papyrus',
    'Trattatello',
    'Snell Roundhand',
    'Zapfino',
    'Herculanum',
  ],
  'text-decoration': [
    'none',
    'underline',
    'overline',
    'line-through',
    'blink',
    'inherit',
    'initial',
    'unset',
  ],
  'text-transform': [
    'none',
    'capitalize',
    'uppercase',
    'lowercase',
    'full-width',
    'inherit',
    'initial',
    'unset',
  ],
  'font-style': ['normal', 'italic', 'oblique', 'inherit', 'initial', 'unset'],
  'border-radius': [
    '0',
    '1px',
    '2px',
    '3px',
    '4px',
    '5px',
    '6px',
    '7px',
    '8px',
    '9px',
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '40px',
    '48px',
    '56px',
    '64px',
    '72px',
  ],
  'box-shadow': [
    'none',
    '0 1px 3px rgba(0,0,0,0.12)',
    '0 1px 2px rgba(0,0,0,0.24)',
    '0 3px 6px rgba(0,0,0,0.16)',
    '0 3px 6px rgba(0,0,0,0.23)',
    '0 10px 20px rgba(0,0,0,0.19)',
    '0 6px 6px rgba(0,0,0,0.23)',
    '0 14px 28px rgba(0,0,0,0.25)',
    '0 10px 10px rgba(0,0,0,0.22)',
    '0 19px 38px rgba(0,0,0,0.30)',
    '0 15px 12px rgba(0,0,0,0.22)',
    '0 0 0 1px rgba(0,0,0,0.1)',
    '0 0 0 2px rgba(0,0,0,0.1)',
    '0 0 0 3px rgba(0,0,0,0.1)',
    '0 0 0 4px rgba(0,0,0,0.1)',
    '0 0 0 5px rgba(0,0,0,0.1)',
  ],
  opacity: ['0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '1'],
  'z-index': [
    'auto',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '10',
    '20',
    '30',
    '40',
    '50',
    '100',
    '1000',
    '9999',
  ],
  display: [
    'none',
    'block',
    'inline',
    'inline-block',
    'flex',
    'inline-flex',
    'grid',
    'inline-grid',
    'table',
    'inline-table',
    'table-row',
    'table-cell',
    'table-column',
    'table-column-group',
    'table-header-group',
    'table-footer-group',
    'table-row-group',
    'table-caption',
    'inherit',
    'initial',
    'unset',
  ],
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky', 'inherit', 'initial', 'unset'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'inherit', 'initial', 'unset'],
  cursor: [
    'auto',
    'default',
    'pointer',
    'text',
    'move',
    'not-allowed',
    'help',
    'wait',
    'crosshair',
    'progress',
    'grab',
    'grabbing',
    'zoom-in',
    'zoom-out',
    'inherit',
    'initial',
    'unset',
  ],
  transition: [
    'none',
    'all 0.3s ease',
    'all 0.5s ease',
    'all 0.7s ease',
    'all 1s ease',
    'opacity 0.3s ease',
    'transform 0.3s ease',
    'background-color 0.3s ease',
    'color 0.3s ease',
    'border 0.3s ease',
  ],
  transform: [
    'none',
    'translateX(10px)',
    'translateY(10px)',
    'translate(10px, 10px)',
    'scale(1.1)',
    'scaleX(1.1)',
    'scaleY(1.1)',
    'rotate(45deg)',
    'rotateX(45deg)',
    'rotateY(45deg)',
    'skew(10deg, 10deg)',
    'skewX(10deg)',
    'skewY(10deg)',
    'matrix(1, 0, 0, 1, 10, 10)',
  ],
};
