export { Editor, type EditorOptions } from './editor/Editor';
export { ParseError } from '@codemerge/kernel';
export {
  TablePlugin,
  createDefaultPlugins,
  defaultTableToolbar,
  emptyEditorDoc,
  emptyTableGrid,
  isTableEditorDoc,
  gridFromDoc,
  gridFromMatrix,
  docFromGrid,
  normalizeTableGrid,
  parseText,
  serializeText,
  serializeDoc,
  MAX_TABLE_BYTES,
  exportCsv,
  gridToHtml,
  htmlToGrid,
  gridToMarkdown,
  markdownToGrid,
  type TablePluginOptions,
  type TablePluginFeatures,
  type TableToolbarOptions,
  type TableToolbarItem,
  type TableToolbarMenu,
  type TableToolbarActionApi,
  type TableGridDoc,
  type TableColumn,
  type TableRow,
  type TableViewState,
  type CellValue,
  type ParseTextResult,
} from '@ocm/table-plugin';
