export { Editor, type EditorOptions } from './editor/Editor';
export { ParseError } from '@ocm/wysiwyg/utils/parseSoT';
export {
  TablePlugin,
  createDefaultPlugins,
  defaultTableToolbar,
  emptyEditorDoc,
  emptyTableGrid,
  isTableEditorDoc,
  gridFromDoc,
  gridFromMatrix,
  docFromGrid,
  normalizeTableGrid,
  parseText,
  serializeText,
  serializeDoc,
  MAX_TABLE_BYTES,
  type TablePluginOptions,
  type TablePluginFeatures,
  type TableToolbarOptions,
  type TableToolbarItem,
  type TableToolbarMenu,
  type TableToolbarActionApi,
  type TableGridDoc,
  type TableColumn,
  type TableRow,
  type TableViewState,
  type CellValue,
  type CellDriver,
  type CellRenderCtx,
  type TableWorkspaceHandle,
  type ParseTextResult,
  exportCsv,
  registerCellDriver,
  getCellDriver,
  TableStore,
  mountTableWorkspace,
} from '@ocm/table-plugin';
